# Generated by Django 3.0.3 on 2022-07-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiScam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='emailOfScamer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
