# Generated by Django 3.0.3 on 2022-07-20 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('antiScam', '0003_stories_scamtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
