# Generated by Django 3.0.3 on 2022-08-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiScam', '0005_cooperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinActivites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitesTitle', models.CharField(blank=True, max_length=256)),
                ('joinerName', models.CharField(blank=True, max_length=256)),
                ('joinerEmail', models.CharField(blank=True, max_length=256)),
                ('joinerContactNumber', models.CharField(blank=True, max_length=256)),
                ('joinAs', models.CharField(blank=True, max_length=256)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
