# Generated by Django 3.0.3 on 2022-08-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiScam', '0006_joinactivites'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinactivites',
            name='joinerDob',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
