# Generated by Django 3.0.3 on 2022-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiScam', '0008_remove_joinactivites_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddActivites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitesTitle', models.CharField(blank=True, max_length=256)),
                ('activitesDetail', models.TextField()),
                ('activitesLocation', models.CharField(blank=True, max_length=256)),
                ('activitesCooperateWith', models.CharField(blank=True, max_length=256)),
                ('activitesTime', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
