# Generated by Django 3.0.3 on 2022-08-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiScam', '0011_auto_20220820_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addactivites',
            old_name='toDo1',
            new_name='toDo',
        ),
        migrations.RemoveField(
            model_name='addactivites',
            name='toDo2',
        ),
        migrations.RemoveField(
            model_name='addactivites',
            name='toDo3',
        ),
    ]
