# Generated by Django 3.0.3 on 2022-08-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiScam', '0013_remove_addactivites_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addactivites',
            name='toDo',
            field=models.TextField(blank=True),
        ),
    ]
