# Generated by Django 3.0.3 on 2022-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiScam', '0014_addactivites_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addactivites',
            name='canJoinAs',
            field=models.TextField(blank=True),
        ),
    ]
